language: node_js
node_js: '6.10'
env:
  global:
    - secure: yTQunPfqSe6FEdmtGIOwN014KEDV0fkTcRUD4tSKy3X65cmju4WUdBYE6rskW4eOvkMH7oMc9DgZ/bo1uAO8dQtRXS/OreSphJDtAapH0RpO1U3yNhur+0kWUJ+yxR6UFj4IyIPrdAFpKaj7USRLYC/7Uax/pfd11P2L3q96VCTIrfyuQgEKlijotDmBJyrOc8O8NePiEoEtmw62XOpPtO5FivLL5ZWz+aJJdKSE8N5J2ubzOc6fKB3mm4M/WRCabcCTDA+jb5XDy3EssnmkM76zXyXLwfMz+36FSh4MHC2Aom5Jboazyiqv7GwVO5jxQ92BeoRNZpkSTR9Avbf+Kw8Fk33f279tsLvA3xSgACeEqsvwPVDQQbNWI+58ByYBAJtER6ZuCl6r5IDSRUboy3uDUthPGRN7Lj4xby34FVvuChMDVe5slTFoqu6XWFFJnNKOLKM3tdZErVgJImUkWSIQlpMeZz2NjYlC2/iL1r7virkO4tJklBW8Lx1WOGSAnNk+Z/14RXVzz2fa/fDE4RAfBmtxdBO0cg5qE6kEfzHlsflFB4PQ2nUjAECSrAkShcbBqMAjOzS2GMD1RGgkeO0qOYVTASGw6maI37XAZwZ9UUhTADOoXKfkN2EbTvwim2us6RNx+CsTBF8mCf8BMApaXf7NlaSDDTO+TssXr9I=
    - secure: NGRJr+mejj2g9bHRjrLbgu1YGGf2T49OruYzLc77aJHAnnyjPjaWv0VC8hwqIOXg5go1FF6GkIkY/t+am8msON92xBsLIrzF5pTbx02mJBlWopt7G46wQ6mVdd+8CKNioRQ/xGCAzLsr5ZzoBlO+DP4yGzY9fLkg6e3/mLCsqAcjBdZOhq4BL+rBZE9WdW2qbZBDMRt/ZvmB0JoV2tN6KCgImUYr6NC4mTS1+r6/qhQq6iutYf7S46O+xuKrbUM28/PJj04V6LgSeUMJ4FtMkujF0tKhqDskqfWpsm32iadrx2MsbOpAFwXt3k5N2hOUDJQ/ubph/ekSdu42eRYZQi1zxbsjR0FVc2zWnLI+75BdsfVFar6QImcGN8u+wMZIJdQ9+sYlNLi4DCAFrqTEonOTpoVIx/BFfQQVhaCZcqeOH+7DmFKq7Dgut/oPdGN/ubW8sm96DJJir3P6MnbtOZFc78H7xWvK9C6TkuCOtER5/85G5KhcIBMmYOtEeh4qCBJ0UThul0LTqC/CnTdmNITCwzEkEypUb6Naqfs76hOofMh/GR3lLoZXKWojHwYYoms9hZUWnNC2BNskwINrPgJ9lrL4BZ2kW17++Qw1nybJxswlbls00G9SH49idST0Z7MCVGf90Ac4DJREdfTleZgaw+uLSSlG+D8DDVJ9Ls4=
before_install:
  - npm install -g serverless
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - cd api && serverless deploy
  - aws s3 cp web s3://brunsviga/ --recursive
